//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсовойПроект
{
    using System;
    using System.Collections.Generic;
    
    public partial class rassrochka
    {
        public int idrassrochka { get; set; }
        public int idagent { get; set; }
        public string index_str { get; set; }
        public int idstrahovately { get; set; }
        public string nomer_dogovora { get; set; }
        public Nullable<System.DateTime> data_nachala { get; set; }
        public Nullable<System.DateTime> data_okonchanya { get; set; }
        public Nullable<decimal> nachisl_str_premya { get; set; }
        public Nullable<decimal> oplach_premya { get; set; }
        public Nullable<int> kol_platezh { get; set; }
        public Nullable<System.DateTime> data_2pl { get; set; }
        public Nullable<System.DateTime> data_3pl { get; set; }
        public Nullable<System.DateTime> data_4pl { get; set; }
        public Nullable<decimal> summa_platezh { get; set; }
        public Nullable<decimal> summa_2pl { get; set; }
        public Nullable<decimal> summa_3pl { get; set; }
        public Nullable<decimal> summa_4pl { get; set; }
        public string bank_posr { get; set; }
        public string primechanya { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual strahovately strahovately { get; set; }
        public virtual strahovki strahovki { get; set; }
    }
}
