//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсовойПроект
{
    using System;
    using System.Collections.Generic;
    
    public partial class strahovki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public strahovki()
        {
            this.edinovr_oplata = new HashSet<edinovr_oplata>();
            this.rassrochka = new HashSet<rassrochka>();
        }
    
        public string index_str { get; set; }
        public string naimenov_str { get; set; }
        public string kategoria_str { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edinovr_oplata> edinovr_oplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rassrochka> rassrochka { get; set; }
    }
}
