//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсовойПроект
{
    using System;
    using System.Collections.Generic;
    
    public partial class strahovately
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public strahovately()
        {
            this.edinovr_oplata = new HashSet<edinovr_oplata>();
            this.rassrochka = new HashSet<rassrochka>();
        }
    
        public int idstrahovately { get; set; }
        public string FIO_Namenov { get; set; }
        public Nullable<System.DateTime> data_rozden { get; set; }
        public string address { get; set; }
        public string rab_telefon { get; set; }
        public string mob_telefon_1 { get; set; }
        public string mob_telefon_2 { get; set; }
        public string dom_telefon { get; set; }
        public string kategorya { get; set; }
        public string primechanya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edinovr_oplata> edinovr_oplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rassrochka> rassrochka { get; set; }
    }
}
